package com.agrioptima.engine.plan;

import com.agrioptima.engine.NutrientAmounts;
import com.agrioptima.engine.plan.FertilizerPlanVerifier.CandidatePlan;
import com.agrioptima.engine.plan.FertilizerPlanVerifier.ClaimedTotals;
import com.agrioptima.engine.plan.FertilizerPlanVerifier.PlanLine;
import com.agrioptima.engine.plan.FertilizerPlanVerifier.PlanVerification;
import com.agrioptima.engine.plan.FertilizerPlanVerifier.ProductSpec;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.StreamSupport;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Re-checks, in Java, plans produced by the real Python optimizer (HiGHS). The fixture is generated by
 * {@code ml-service: python -m tests.optimizer_contract}; a pytest fails if it no longer matches the optimizer.
 */
class FertilizerPlanVerifierContractTest {

    private static List<JsonNode> cases;

    @BeforeAll
    static void load() throws IOException {
        try (InputStream in = FertilizerPlanVerifierContractTest.class
                .getResourceAsStream("/optimizer/optimizer-contract.json")) {
            assertThat(in).as("optimizer-contract.json on the test classpath").isNotNull();
            cases = StreamSupport.stream(new ObjectMapper().readTree(in).get("cases").spliterator(), false).toList();
        }
    }

    @Test
    void everyOptimizerPlanPassesTheIndependentRecheck() {
        int plansChecked = 0;
        for (JsonNode c : cases) {
            for (JsonNode plan : c.get("response").get("plans")) {
                PlanVerification v = verify(c, candidate(plan, 1.0));
                assertThat(v.violations()).as(c.get("name").asText() + " / " + v.strategy()).isEmpty();
                assertThat(v.valid()).isTrue();
                assertThat(v.costPerHa()).isEqualTo(plan.get("cost_per_ha").asDouble(),
                        org.assertj.core.api.Assertions.within(1e-9 * Math.max(1, v.costPerHa())));
                plansChecked++;
            }
        }
        assertThat(plansChecked).isEqualTo(27); // 9 cases with plans x 3 strategies
    }

    @Test
    void removingOnePercentOfEveryProductBreaksARequirement() {
        for (JsonNode c : cases) {
            if (!c.get("response").get("status").asText().equals("OPTIMAL")) {
                continue;
            }
            for (JsonNode plan : c.get("response").get("plans")) {
                PlanVerification v = verify(c, candidate(plan, 0.99));
                assertThat(v.valid()).as(c.get("name").asText()).isFalse();
                assertThat(v.violations()).anyMatch(s -> s.contains("requirement is"));
            }
        }
    }

    @Test
    void aPriceChangeSinceTheOptimizerRanIsDetected() {
        JsonNode c = cases.stream().filter(n -> n.get("name").asText().equals("m4_3_wheat_low_soil")).findFirst()
                .orElseThrow();
        List<ProductSpec> catalogue = new ArrayList<>(catalogue(c));
        catalogue.replaceAll(p -> p.code().equals("DAP")
                ? new ProductSpec("DAP", p.nPct(), p.p2o5Pct(), p.k2oPct(), 28.00, p.maxKgHa()) : p);
        PlanVerification v = FertilizerPlanVerifier.verify(required(c), c.get("request").get("area_ha").asDouble(),
                catalogue, candidate(c.get("response").get("plans").get(0), 1.0));
        assertThat(v.valid()).isFalse();
        assertThat(v.violations()).anyMatch(s -> s.startsWith("cost per ha"));
    }

    @Test
    void infeasibleAndNothingRequiredCasesCarryNoViolatingPlan() {
        JsonNode infeasible = byName("infeasible_no_potash").get("response");
        assertThat(infeasible.get("status").asText()).isEqualTo("INFEASIBLE");
        assertThat(infeasible.get("plans")).isEmpty();
        assertThat(infeasible.get("infeasibility").get(0).get("nutrient").asText()).isEqualTo("K2O");

        JsonNode nothing = byName("nothing_required").get("response");
        assertThat(nothing.get("status").asText()).isEqualTo("NOTHING_REQUIRED");
        nothing.get("plans").forEach(p -> assertThat(p.get("items")).isEmpty());
    }

    private static JsonNode byName(String name) {
        return cases.stream().filter(n -> n.get("name").asText().equals(name)).findFirst().orElseThrow();
    }

    private static PlanVerification verify(JsonNode c, CandidatePlan plan) {
        return FertilizerPlanVerifier.verify(required(c), c.get("request").get("area_ha").asDouble(), catalogue(c),
                plan);
    }

    private static NutrientAmounts required(JsonNode c) {
        return amounts(c.get("request").get("requirement_kg_ha"));
    }

    private static List<ProductSpec> catalogue(JsonNode c) {
        double defaultCap = c.get("request").get("parameters").get("default_max_kg_ha").asDouble();
        List<ProductSpec> out = new ArrayList<>();
        for (JsonNode f : c.get("request").get("fertilizers")) {
            JsonNode cap = f.get("max_kg_ha");
            out.add(new ProductSpec(f.get("code").asText(), f.get("n_pct").asDouble(), f.get("p2o5_pct").asDouble(),
                    f.get("k2o_pct").asDouble(), f.get("price_per_kg").asDouble(),
                    cap == null || cap.isNull() ? defaultCap : cap.asDouble()));
        }
        return out;
    }

    /** The plan as the optimizer returned it; {@code scale != 1} tampers with the quantities only. */
    private static CandidatePlan candidate(JsonNode plan, double scale) {
        List<PlanLine> lines = new ArrayList<>();
        for (JsonNode item : plan.get("items")) {
            lines.add(new PlanLine(item.get("code").asText(), item.get("kg_ha").asDouble() * scale,
                    item.get("field_kg").asDouble() * scale));
        }
        ClaimedTotals claimed = scale != 1.0 ? null : new ClaimedTotals(
                amounts(plan.get("supplied_kg_ha")), amounts(plan.get("supplied_field_kg")),
                amounts(plan.get("excess_kg_ha")), amounts(plan.get("excess_field_kg")),
                plan.get("cost_per_ha").asDouble(), plan.get("field_cost").asDouble(),
                plan.get("total_mass_kg_ha").asDouble(), plan.get("total_mass_field_kg").asDouble(),
                plan.get("feasible").asBoolean());
        return new CandidatePlan(plan.get("strategy").asText(), lines, claimed);
    }

    private static NutrientAmounts amounts(JsonNode n) {
        return new NutrientAmounts(n.get("n").asDouble(), n.get("p2o5").asDouble(), n.get("k2o").asDouble());
    }
}
