"""Fertilizer catalogue and optimizer contract cases shared by the tests and the backend.

The catalogue is the backend's V2 reference data (checked against the migration in test_optimizer.py). The contract
cases are solved with the real optimizer and written to the backend test resources, where
``FertilizerPlanVerifierContractTest`` re-checks every plan in Java.

Regenerate after an intentional optimizer change:  python -m tests.optimizer_contract
"""

from __future__ import annotations

import json
from pathlib import Path

from app.optimizer import OptimizationRequest, optimize

REPO_ROOT = Path(__file__).resolve().parents[2]
V2_MIGRATION = REPO_ROOT / "backend/src/main/resources/db/migration/V2__reference_data.sql"
CONTRACT_FILE = REPO_ROOT / "backend/src/test/resources/optimizer/optimizer-contract.json"

V2_FERTILIZERS = [
    {"code": "UREA", "name": "Urea", "n_pct": 46.0, "p2o5_pct": 0.0, "k2o_pct": 0.0, "price_per_kg": 5.92},
    {"code": "DAP", "name": "Diammonium Phosphate (DAP)", "n_pct": 18.0, "p2o5_pct": 46.0, "k2o_pct": 0.0,
     "price_per_kg": 27.00},
    {"code": "MOP", "name": "Muriate of Potash (MOP)", "n_pct": 0.0, "p2o5_pct": 0.0, "k2o_pct": 60.0,
     "price_per_kg": 34.00},
    {"code": "NPK_10_26_26", "name": "NPK Complex 10:26:26", "n_pct": 10.0, "p2o5_pct": 26.0, "k2o_pct": 26.0,
     "price_per_kg": 29.40},
    {"code": "SSP", "name": "Single Super Phosphate (SSP)", "n_pct": 0.0, "p2o5_pct": 16.0, "k2o_pct": 0.0,
     "price_per_kg": 11.00},
]


def request(n, p2o5, k2o, area_ha=1.0, fertilizers=None, **parameters) -> OptimizationRequest:
    body = {
        "requirement_kg_ha": {"n": n, "p2o5": p2o5, "k2o": k2o},
        "area_ha": area_ha,
        "fertilizers": V2_FERTILIZERS if fertilizers is None else fertilizers,
    }
    if parameters:
        body["parameters"] = parameters
    return OptimizationRequest.model_validate(body)


def only(*codes, **overrides) -> list[dict]:
    """Subset of the V2 catalogue; ``overrides={"SSP": {"max_kg_ha": 700}}`` style changes via keyword."""
    return [{**f, **overrides.get(f["code"], {})} for f in V2_FERTILIZERS if f["code"] in codes]


# Requirements are Milestone 4 engine outputs (docs/RECOMMENDATION_ENGINE.md §5) plus edge cases.
CONTRACT_CASES = {
    "m4_1_wheat_cri_n_only": request(40, 0, 0, area_ha=2.0),
    "m4_3_wheat_low_soil": request(100, 75, 50, area_ha=2.0),
    "m4_4_rice_panicle_initiation": request(67.5, 45, 22.5, area_ha=0.5),
    "m4_5_maize_rainfed": request(30, 30, 30, area_ha=1.2),
    "m4_6_wheat_p_k_only": request(0, 60, 40, area_ha=1.0),
    "tiny_field": request(33.333333333333336, 0.1, 0.2, area_ha=0.001),
    "huge_field": request(120, 60, 40, area_ha=250_000),
    "upper_bound_binding": request(90, 0, 0, fertilizers=only("UREA", "DAP", "SSP", UREA={"max_kg_ha": 100})),
    "nothing_required": request(0, 0, 0),
    "infeasible_no_potash": request(40, 30, 20, fertilizers=only("UREA", "DAP")),
}


def contract_document() -> dict:
    return {
        "_comment": "Generated by ml-service `python -m tests.optimizer_contract` from actual HiGHS output. Do not edit.",
        "cases": [
            {"name": name, "request": req.model_dump(mode="json"), "response": optimize(req).model_dump(mode="json")}
            for name, req in CONTRACT_CASES.items()
        ],
    }


def render() -> str:
    return json.dumps(contract_document(), indent=2) + "\n"


if __name__ == "__main__":
    CONTRACT_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_FILE.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {CONTRACT_FILE}")
