package com.agrioptima.integration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UncheckedIOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.function.Function;

/**
 * Stand-in for the FastAPI ML service in integration tests.
 *
 * <p>{@code /optimize} replays <b>real optimizer output</b>: the response recorded for the matching request in
 * {@code optimizer/optimizer-contract.json} (generated by the Python optimizer, Milestone 5). {@code /predict-yield}
 * returns a deterministic function of the scenario ({@link #yieldOf}) so tests can check that every plan gets the
 * prediction for its own scenario. Handlers can be replaced per test.
 */
final class FakeMlService {

    record Reply(int status, String body) {
        static Reply json(Object node) {
            return new Reply(200, node.toString());
        }

        static Reply problem(int status, String type) {
            return new Reply(status, """
                    {"type":"urn:agrioptima:problem:%s","title":"t","status":%d,"detail":"d"}""".formatted(type, status));
        }
    }

    static final ObjectMapper MAPPER = new ObjectMapper();
    static final String MODEL_VERSION = "fake-yield-model-1";
    private static final JsonNode CONTRACT = load();

    private final HttpServer server;
    final List<JsonNode> optimizeRequests = new CopyOnWriteArrayList<>();
    final List<JsonNode> predictRequests = new CopyOnWriteArrayList<>();
    volatile Function<JsonNode, Reply> optimize = FakeMlService::contractReplay;
    volatile Function<JsonNode, Reply> predict = FakeMlService::predictions;

    FakeMlService() {
        try {
            server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        server.createContext("/optimize", ex -> handle(ex, optimizeRequests, optimize));
        server.createContext("/predict-yield", ex -> handle(ex, predictRequests, predict));
        server.setExecutor(Executors.newCachedThreadPool());
        server.start();
    }

    String baseUrl() {
        return "http://127.0.0.1:" + server.getAddress().getPort();
    }

    void reset() {
        optimizeRequests.clear();
        predictRequests.clear();
        optimize = FakeMlService::contractReplay;
        predict = FakeMlService::predictions;
    }

    static JsonNode tree(String json) {
        try {
            return MAPPER.readTree(json);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Deterministic fake yield (t/ha) for a scenario. */
    static double yieldOf(JsonNode scenario) {
        return 2.0 + scenario.path("n_kg_ha").asDouble() / 100 + scenario.path("p2o5_kg_ha").asDouble() / 1000
                + scenario.path("k2o_kg_ha").asDouble() / 10000;
    }

    /** Real optimizer response for the contract case with the same requirement and area. */
    static Reply contractReplay(JsonNode request) {
        for (JsonNode c : CONTRACT.path("cases")) {
            JsonNode r = c.path("request");
            if (r.path("requirement_kg_ha").equals(normalise(request.path("requirement_kg_ha")))
                    && r.path("area_ha").asDouble() == request.path("area_ha").asDouble()) {
                ObjectNode response = c.path("response").deepCopy();
                response.put("feasible", !"INFEASIBLE".equals(response.path("status").asText()));
                return Reply.json(response);
            }
        }
        return Reply.problem(500, "internal");
    }

    /** Predictions in reverse order (the backend must map them by index, not by position). */
    static Reply predictions(JsonNode request) {
        ObjectNode body = MAPPER.createObjectNode();
        body.put("model_version", MODEL_VERSION).put("feature_version", "f").put("unit", "t/ha")
                .put("extrapolation", false).putArray("warnings");
        ArrayNode out = body.putArray("predictions");
        JsonNode scenarios = request.path("scenarios");
        for (int i = scenarios.size() - 1; i >= 0; i--) {
            JsonNode s = scenarios.get(i);
            out.addObject().put("index", i).put("crop", s.path("crop").asText())
                    .put("predicted_yield_t_ha", Math.round(yieldOf(s) * 1000) / 1000.0)
                    .put("extrapolation", false).put("model_version", MODEL_VERSION).putArray("clipped_features");
        }
        return Reply.json(body);
    }

    /** Requirement values as doubles, so 40 and 40.0 compare equal to the fixture. */
    private static JsonNode normalise(JsonNode requirement) {
        ObjectNode n = MAPPER.createObjectNode();
        requirement.fields().forEachRemaining(e -> n.put(e.getKey(), e.getValue().asDouble()));
        return n;
    }

    private static void handle(HttpExchange ex, List<JsonNode> log, Function<JsonNode, Reply> handler)
            throws IOException {
        try (ex) {
            JsonNode request;
            try (InputStream in = ex.getRequestBody()) {
                request = MAPPER.readTree(in);
            }
            log.add(request);
            Reply reply = handler.apply(request);
            byte[] bytes = reply.body().getBytes(StandardCharsets.UTF_8);
            ex.getResponseHeaders().add("Content-Type",
                    reply.status() >= 400 ? "application/problem+json" : "application/json");
            ex.sendResponseHeaders(reply.status(), bytes.length);
            try (OutputStream out = ex.getResponseBody()) {
                out.write(bytes);
            }
        }
    }

    private static JsonNode load() {
        try (InputStream in = FakeMlService.class.getResourceAsStream("/optimizer/optimizer-contract.json")) {
            ObjectNode doc = (ObjectNode) MAPPER.readTree(in);
            // fixture requirements are already doubles; keep a normalised copy for matching
            for (JsonNode c : doc.path("cases")) {
                ((ObjectNode) c.path("request")).set("requirement_kg_ha", normalise(c.path("request").path("requirement_kg_ha")));
            }
            return doc;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
